timestamp() {
  date +"%Y%m%d%H%M%S"
}
git init
echo Adding all files to commit...
git add .
echo Uploading commit...
git commit -m "Updated Local Repo $(timestamp)"
echo Pulling origin...
git pull origin master
echo Pushing...
git push origin master
echo Done!
